"""
In-memory analysis snapshot cache.

Design intent:
- Each run_id maps to ONE authoritative analysis snapshot.
- Snapshot is generated by analysis_engine.run_full_analysis().
- Snapshot may be overwritten for the SAME run_id (intentional).
- Used to prevent stale dashboards and cross-run contamination.

Eviction:
- Maximum _STORE_MAX_SIZE snapshots kept in memory.
- Oldest entry (FIFO) evicted when capacity is reached.
- Prevents unbounded memory growth on servers that process many uploads.

Scope:
- Single-process / lab / SOC simulation use.
- NOT thread-safe or multi-worker safe by design.
- In production, replace with Redis / task-result store.
"""

import threading
from typing import Dict, List, Optional, Tuple

# -------------------------------------------------------------------
# Internal store
# -------------------------------------------------------------------

_ANALYSIS_STORE: Dict[str, dict] = {}   # { run_id: analysis_context }
_STORE_ORDER:    List[str]        = []   # insertion-order list for FIFO eviction
_STORE_LOCK      = threading.Lock()      # protects both store and order list
_STORE_MAX_SIZE  = 100                   # max snapshots in memory before eviction (Phase 9)

import logging
import time
log = logging.getLogger("analysis_cache")

# -------------------------------------------------------------------
# Hybrid Versioning (The 10/10 Integrity Phase)
# -------------------------------------------------------------------

_SNAPSHOT_VERSIONS: Dict[str, Tuple[float, float]] = {}  # { run_id: (monotonic, unix) }

# ---------------------------------------------------
# Snapshot API
# ---------------------------------------------------

def set_analysis_snapshot(run_id: str, snapshot: dict) -> None:
    """
    Store analysis snapshot for a specific run_id with hybrid versioning and validation.
    """
    if not run_id or snapshot is None:
        return

    # 🔥 Integrity validation (Stop the "Ghost UI" bug)
    if not snapshot.get("timeline") and not snapshot.get("burst_aggregates"):
        log.warning(f"[Cache] Rejected empty snapshot for run_id={run_id[:16]} (No timeline/bursts)")
        return

    with _STORE_LOCK:
        if run_id not in _ANALYSIS_STORE and len(_ANALYSIS_STORE) >= _STORE_MAX_SIZE:
            if _STORE_ORDER:
                oldest = _STORE_ORDER.pop(0)
                _ANALYSIS_STORE.pop(oldest, None)
                _SNAPSHOT_VERSIONS.pop(oldest, None)
                log.info(f"[Cache] Evicted oldest snapshot (run_id={oldest[:16]}) to free space")

        # 🔥 Hybrid Versioning: (monotonic for sequence, time for wall-clock sanity)
        _SNAPSHOT_VERSIONS[run_id] = (time.monotonic(), time.time())
        _ANALYSIS_STORE[run_id] = snapshot
        
        if run_id in _STORE_ORDER:
            _STORE_ORDER.remove(run_id)
        _STORE_ORDER.append(run_id)
        log.debug(f"[Cache] Snapshot set: run_id={run_id[:16]}, size={len(str(snapshot))}")


def get_analysis_snapshot(run_id: str) -> Optional[dict]:
    """
    Retrieve analysis snapshot for a run_id with integrity check.
    """
    if not run_id:
        return None
    with _STORE_LOCK:
        snapshot = _ANALYSIS_STORE.get(run_id)
        if snapshot:
            # 🔥 Defensive integrity check: ensure snapshot wasn't partially cleared
            if not snapshot.get("timeline") and not snapshot.get("burst_aggregates"):
                return None
            return snapshot
        return None


def clear_analysis_snapshot(run_id: Optional[str] = None, *, clear_all: bool = False) -> None:
    """
    Clear cached analysis snapshots.

    Modes:
    - run_id provided → clears only that run's snapshot
    - clear_all=True  → clears ALL snapshots (explicit only)
    """
    with _STORE_LOCK:
        if run_id:
            _ANALYSIS_STORE.pop(run_id, None)
            if run_id in _STORE_ORDER:
                _STORE_ORDER.remove(run_id)
            return

        if clear_all:
            _ANALYSIS_STORE.clear()
            _STORE_ORDER.clear()


# -------------------------------------------------------------------
# Diagnostics / Debug
# -------------------------------------------------------------------

def _debug_cache_state() -> dict:
    """INTERNAL USE ONLY. Returns cache metadata for debugging."""
    with _STORE_LOCK:
        return {
            "total_runs":  len(_ANALYSIS_STORE),
            "max_size":    _STORE_MAX_SIZE,
            "run_ids":     list(_ANALYSIS_STORE.keys()),
            "evict_order": list(_STORE_ORDER),
        }
