"""
In-memory analysis snapshot cache.

Design intent:
- Each run_id maps to ONE authoritative analysis snapshot.
- Snapshot is generated by analysis_engine.run_full_analysis().
- Snapshot may be overwritten for the SAME run_id (intentional).
- Used to prevent stale dashboards and cross-run contamination.

Eviction:
- Maximum _STORE_MAX_SIZE snapshots kept in memory.
- Oldest entry (FIFO) evicted when capacity is reached.
- Prevents unbounded memory growth on servers that process many uploads.

Scope:
- Single-process / lab / SOC simulation use.
- NOT thread-safe or multi-worker safe by design.
- In production, replace with Redis / task-result store.
"""

import threading
from typing import Dict, List, Optional, Tuple

# -------------------------------------------------------------------
# Internal store
# -------------------------------------------------------------------

_ANALYSIS_STORE: Dict[str, dict] = {}   # { run_id: analysis_context }
_STORE_ORDER:    List[str]        = []   # insertion-order list for FIFO eviction
_STORE_LOCK      = threading.Lock()      # protects both store and order list
_STORE_MAX_SIZE  = 100                   # max snapshots in memory before eviction (Phase 9)
_SNAPSHOT_VERSIONS: Dict[str, int] = {}  # { run_id: current_version_counter }

import logging
import copy

import time
log = logging.getLogger("analysis_cache")

# -------------------------------------------------------------------
# Hybrid Versioning & Status Guards (The 10/10 Certification Phase)
# -------------------------------------------------------------------
# Atomic stage priorities for monotonic progress
STAGE_ORDER = {"primary": 1, "insight": 2, "fused": 3}

# ---------------------------------------------------
# Snapshot API
# ---------------------------------------------------

def _normalize_snapshot(snapshot: dict) -> dict:
    """Production-grade schema enforcement on read. Prevents mutation of shared cache."""
    if not isinstance(snapshot, dict):
        return None

    # 🔥 Lock memory: prevent cross-request mutation
    snap = copy.deepcopy(snapshot)

    # 🔒 Strict Schema Enforcement
    snap["timeline"] = snap.get("timeline") or []
    snap["burst_aggregates"] = snap.get("burst_aggregates") or []

    # 🔒 Status Normalization — ensure UI always has a definitive state
    raw_status = snap.get("status", "")
    if raw_status not in ("complete", "failed", "processing", "degraded"):
        snap["status"] = "complete"  # Default to complete for legacy snapshots

    # 🔒 Timeline Guard — log error if timeline is missing structure
    if "timeline" not in snapshot:
        log.error("[CACHE] Invalid snapshot schema: 'timeline' key missing for run_id lookup")

    narrative = snap.get("attack_narrative") or {}
    snap["attack_narrative"] = {
        "summary": narrative.get("summary", "No threats detected"),
        "stage": narrative.get("stage", "None"),
        "score": float(narrative.get("score", 0)),
        "is_attack": bool(narrative.get("is_attack", False))
    }

    return snap

def set_analysis_snapshot(run_id: str, snapshot: dict) -> None:
    """
    Store analysis snapshot for a specific run_id with hybrid versioning and validation.
    """
    if not run_id or snapshot is None:
        return

    if not isinstance(snapshot, dict):
        log.warning(f"[Cache] Invalid snapshot type for run_id={run_id[:16]}")
        return

    # Schema guard: ensure required fields are present before storing
    if "timeline" not in snapshot:
        log.error("[Cache] Snapshot missing 'timeline' key for run_id=%s — storing anyway", run_id[:16])
        snapshot = dict(snapshot)  # Don't mutate caller's dict
        snapshot["timeline"] = []

    # Ensure status is always set
    if "status" not in snapshot:
        snapshot = dict(snapshot)
        snapshot["status"] = "complete"

    # 🔒 Stage Dominance (Provable Consistency)
    incoming_stage = snapshot.get("pipeline_stage", "primary")
    
    with _STORE_LOCK:
        # DB-Backed Cancellation Shield (Inside Lock)
        # Prevents "Ghost Writes" if cancel happened while acquiring lock.
        from dashboard.db import is_run_cancelled_db
        if is_run_cancelled_db(run_id):
            log.warning(f"[Cache] PROTECTED: Rejected write for CANCELLED run_id={run_id[:16]}")
            return

        existing = _ANALYSIS_STORE.get(run_id)
        if existing:
            existing_stage = existing.get("pipeline_stage", "primary")
            if STAGE_ORDER.get(incoming_stage, 0) < STAGE_ORDER.get(existing_stage, 0):
                log.warning(f"[Cache] PROTECTED: Rejected regressive write ({incoming_stage} < {existing_stage}) for run_id={run_id[:16]}")
                return

        # 🔥 10/10 ATOMIC SWAP / DEEP-COPY ISOLATION
        # We 100% isolate cache from worker mutations.
        current_ver = _SNAPSHOT_VERSIONS.get(run_id, 0) + 1
        new_snap = copy.deepcopy(snapshot)
        new_snap["version"] = current_ver
        new_snap["updated_at"] = time.time()
        
        # Guard against corruption
        if "timeline" not in new_snap: new_snap["timeline"] = []
        if "burst_aggregates" not in new_snap: new_snap["burst_aggregates"] = []
        
        # Atomic Swap
        _ANALYSIS_STORE[run_id] = new_snap
        _SNAPSHOT_VERSIONS[run_id] = current_ver
        
        if run_id in _STORE_ORDER:
            _STORE_ORDER.remove(run_id)
        _STORE_ORDER.append(run_id)
        log.info(f"[Cache] Snapshot MASTER SWAP: run_id={run_id[:16]}, stage={incoming_stage}, version={current_ver}")


def get_analysis_snapshot(run_id: str) -> Optional[dict]:
    """
    Retrieve analysis snapshot for a run_id with mutation-safe normalization.
    """
    if not run_id:
        return None
    with _STORE_LOCK:
        snapshot = _ANALYSIS_STORE.get(run_id)
        if snapshot:
            return _normalize_snapshot(snapshot)
        return None


def clear_analysis_snapshot(run_id: Optional[str] = None, *, clear_all: bool = False) -> None:
    """
    Clear cached analysis snapshots.

    Modes:
    - run_id provided → clears only that run's snapshot
    - clear_all=True  → clears ALL snapshots (explicit only)
    """
    with _STORE_LOCK:
        if run_id:
            _ANALYSIS_STORE.pop(run_id, None)
            if run_id in _STORE_ORDER:
                _STORE_ORDER.remove(run_id)
            return

        if clear_all:
            _ANALYSIS_STORE.clear()
            _STORE_ORDER.clear()


# -------------------------------------------------------------------
# Diagnostics / Debug
# -------------------------------------------------------------------

def _debug_cache_state() -> dict:
    """INTERNAL USE ONLY. Returns cache metadata for debugging."""
    with _STORE_LOCK:
        return {
            "total_runs":  len(_ANALYSIS_STORE),
            "max_size":    _STORE_MAX_SIZE,
            "run_ids":     list(_ANALYSIS_STORE.keys()),
            "evict_order": list(_STORE_ORDER),
        }
